lista = []
print(type(lista))
print(dir(lista))
print(len(lista))
lista.append(1)
print(lista)
lista.append(5)
print(lista)
print(len(lista))
nova_lista = [1, 5, 'Ana', 'Bia']
print(nova_lista)
print(nova_lista.remove(5))
print(nova_lista)
print(nova_lista.reverse())
print(nova_lista)